---
kind: pipeline
type: kubernetes
name: Hello World

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

concurrency:
  limit: 1

environment:
  DOCKER_HOST: tcp://docker-in-docker:2375
  DOCKER_CLI_EXPERIMENTAL: enabled

steps:
  - name: Waiting for Docker to start
    image: harbor.coxedgecomputing.com/coxedge/docker-buildx:20.10.14-0.8.2
    commands:
    - echo 'Waiting for docker to start...'
    - while ! docker info; do sleep 1; done

  - name: Docker-Build
    image: harbor.coxedgecomputing.com/coxedge/docker-buildx:20.10.14-0.8.2
    commands:
    - docker version
    - docker buildx version
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --name multiarch --use
    - docker buildx build --platform linux/amd64,linux/arm64 -f ./Dockerfile ./

  - name: Docker-Publish
    image: harbor.coxedgecomputing.com/coxedge/docker-buildx:20.10.14-0.8.2
    environment:
      DOCKER_USERNAME:
        from_secret: harbor-username
      DOCKER_PASSWORD:
        from_secret: harbor-password
    commands:
    - docker version
    - docker buildx version
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --name multiarch --use
    - docker buildx build --platform linux/amd64,linux/arm64 -t harbor.coxedgecomputing.com/coxedge/hello-world:latest -t harbor.coxedgecomputing.com/coxedge/hello-world:${DRONE_BUILD_NUMBER} --push -f ./Dockerfile ./ 
    when:
      event:
      - deployment
      - promote

services:
- name: docker-in-docker
  docker:
  image: harbor.coxedgecomputing.com/coxedge/docker:20.10.14-dind
  command: ["dockerd", "--host", "0.0.0.0", "--experimental"]
  privileged: true